FROM ubuntu:14.04
WORKDIR /workspace/godemo
ADD . /workspace/godemo

RUN echo 'Install toolset ...'
RUN sudo apt-get update
RUN sudo apt-get install -y npm nodejs-legacy nginx

RUN echo 'Install dependencies ...'
RUN npm install -g grunt-cli bower
RUN npm install
RUN bower install --allow-root

RUN echo 'Build ...'
RUN grunt distribute

RUN echo 'Prepare service ...'
RUN sudo rm -rf /var/www/godemo
RUN sudo mkdir -p /var/www
RUN sudo cp -r ./temp /var/www/godemo
RUN sudo rm -rf /etc/nginx/sites-enabled/default
RUN sudo ln -s $(pwd)/nginx.conf /etc/nginx/sites-enabled/default

ENTRYPOINT ["/workspace/godemo/entrypoint.sh"]
